# Site settings
title: My awesome title
email: your-email@domain.com
description: "Alex Codreanu's personal website. Web developer and constant learner."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
